source 'https://rubygems.org'
ruby '2.2.2'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.1.6'
# Use postgresql as the database for Active Record
gem 'pg'
# Use SCSS for stylesheets
gem 'sass-rails', '~> 5.0.3'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# Use CoffeeScript for .js.coffee assets and views
gem 'coffee-rails', '~> 4.0.0'
# See https://github.com/sstephenson/execjs#readme for more supported runtimes
# gem 'therubyracer',  platforms: :ruby

# Use jquery as the JavaScript library
gem 'jquery-rails'

# Font Awesome
gem 'font-awesome-sass'
# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
# gem 'turbolinks'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.0'
gem 'json', '~> 1.8.2'
# bundle exec rake doc:rails generates the API under doc/api.
gem 'sdoc', '~> 0.4.0',          group: :doc

# Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
gem 'spring',        group: :development

# Google APIs
gem 'google-api-client'

#RSS Builder
gem 'builder'

# File Upload
gem 'carrierwave'

# Fog
gem 'fog'

# Use ActiveModel has_secure_password
gem 'bcrypt', '~> 3.1.7'

# Markdown
gem 'redcarpet'

# Nested Form Fields
gem 'nested_form_fields'

# Mail Form
gem 'mail_form'

# Mailchimp
gem 'mailchimp-api', require: 'mailchimp'

# Foundation
gem 'foundation-rails'
# Use unicorn as the app server
# gem 'unicorn'

# Soundcloud
gem 'soundcloud'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

# Use debugger
gem 'byebug', group: [:development, :test]

